// Copied from PB since mixins cant be used across translation units
mixin class PBX_BetterPickupSound
{
	override void PlayPickupSound(actor toucher)
	{
		let hnd  = PB_EventHandler(EventHandler.Find("PB_EventHandler"));
		if(hnd)
		{
			if(hnd.pickuptic[toucher.PlayerNumber()]==gametic) return;
			hnd.pickuptic[toucher.PlayerNumber()] = gametic;
		}
		double atten;
		int flags = CHANF_OVERLAP|CHANF_MAYBE_LOCAL;
		if(bNoAttenPickupSound) atten = ATTN_NONE;
		else atten = ATTN_NORM;
		if(toucher && toucher.CheckLocalView()) flags |= CHANF_NOPAUSE;
		toucher.A_StartSound(PickupSound,1002,flags,1.0,atten);
	}
}

// Not technically a mixin
// Call in BeginPlay()
struct PBXCore_Duration
{
	// Just in case
	static int GetByCVar(name cvr)
    {
        let c = CVar.FindCVar(cvr);
        return c ? c.GetInt() * Object.TICRATE : 1; // So its always in seconds
    }

	static name GetPBXPowerupDuration(actor mActor)
	{
		switch(mActor.getClassName())
		{
			// Special Powerups
			case 'PBX_PowerInvisTainted': 	 return 'pbx_invistaint_duration';
			case 'PBX_PowerDeflect': 		 return 'pbx_deflect_duration';
			case 'PBX_PowerElectAura': 	 	 return 'pbx_electaura_duration';
			case 'PBX_PowerInvulTainted': 	 return 'pbx_invultaint_duration';
			// Vanilla Powerups
			case 'PBX_PowerBuddha': 		 return 'pbx_buddha_duration';
			case 'PBX_PowerDrain': 		 	 return 'pbx_drain_duration';
			case 'PBX_PowerFlight': 		 return 'pbx_flight_duration';
			case 'PBX_PowerFrightener': 	 return 'pbx_frightener_duration';
			case 'PBX_PowerHighJump': 		 return 'pbx_highjump_duration';
			case 'PBX_PowerInfiniteAmmo': 	 return 'pbx_infammo_duration';
			case 'PBX_PowerProtection': 	 return 'pbx_protect_duration';
			case 'PBX_PowerReflection': 	 return 'pbx_reflect_duration';
			case 'PBX_PowerRegeneration': 	 return 'pbx_regen_duration';
			case 'PBX_PowerTimeFreezer': 	 return 'pbx_timefreeze_duration';
			case 'PBX_PowerTaintedRegen': 	 return 'pbx_taintregen_duration';
			// New Powerups
			case 'PBX_PowerFrostAura': 	 	 return 'pbx_frostaura_duration';
			case 'PBX_PowerFireAura': 		 return 'pbx_fireaura_duration';
		}
		return '';
	}
}

mixin class PBX_PowerupTimer
{
	int time;
	bool lf;

	override void BeginPlay()
	{
		super.BeginPlay();
		PBXCore_Duration dur;
		name cvr = dur.GetPBXPowerupDuration(self);
		EffectTics = cvr != '' ? dur.GetByCVar(cvr) : 0;
	}

	void PowerupTimer(color col, color col2 = 0)
	{
		time = EffectTics;
		switch(time)
		{
			case 105:
			case 70:
			case 35:
				lf = CVar.GetCVar("pb_lowflashesmode", owner.player).GetBool();
				owner.A_SetBlend(col, lf ? 0.08 : 0.25, lf ? 20 : 12, col2);
				owner.A_StartSound("powerup/countdown", CHAN_AUTO, CHANF_OVERLAP | CHANF_UI);
			default:
				break;
		}
	}
	
	void EndBlend(color col, color col2 = 0)
	{ 
		owner.A_SetBlend(col, lf ? 0.1 : 0.50, 35, col2);
		owner.A_StartSound("powerup/ranout", CHAN_AUTO, CHANF_OVERLAP | CHANF_UI); 
	}
}